betterme/forms/user.py
# -*- coding: utf-8 -*-
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, HiddenField, ValidationError
from wtforms.validators import DataRequired, Length, Email, EqualTo, Optional, Regexp

from betterme.models import User


class EditProfileForm(FlaskForm):
    name = StringField('姓名', validators=[DataRequired(), Length(1, 30)])
    username = StringField('用户名', validators=[DataRequired(), Length(1, 20),
                                                   Regexp('^[a-zA-Z0-9]*$',
                                                          message='The username should contain only a-z, A-Z and 0-9.')])
    website = StringField('个人网站', validators=[Optional(), Length(0, 255)])
    location = StringField('城市', validators=[Optional(), Length(0, 50)])
    bio = TextAreaField('个人简介', validators=[Optional(), Length(0, 120)])
    submit = SubmitField('提交')

    def validate_username(self, field):
        if field.data != current_user.username and User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已被占用')


class UploadAvatarForm(FlaskForm):
    image = FileField('上传头像', validators=[
        FileRequired(),
        FileAllowed(['jpg', 'png'], '文件格式应为JPG或PNG格式')
    ])
    submit = SubmitField('上传')


class CropAvatarForm(FlaskForm):
    x = HiddenField()
    y = HiddenField()
    w = HiddenField()
    h = HiddenField()
    submit = SubmitField('裁剪并更新')


class ChangeEmailForm(FlaskForm):
    email = StringField('新邮箱', validators=[DataRequired(), Length(1, 254), Email()])
    submit = SubmitField('提交')


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('旧密码', validators=[DataRequired()])
    password = PasswordField('新密码', validators=[
        DataRequired(), Length(8, 128), EqualTo('password2')])
    password2 = PasswordField('确认密码', validators=[DataRequired()])
    submit = SubmitField('提交')


class NotificationSettingForm(FlaskForm):
    receive_comment_notification = BooleanField('接收新评论提醒')
    receive_follow_notification = BooleanField('接收新粉丝提醒')
    receive_collect_notification = BooleanField('接收新收藏提醒')
    submit = SubmitField('提交')


class PrivacySettingForm(FlaskForm):
    public_collections = BooleanField('公开我的收藏')
    submit = SubmitField('提交')


class DeleteAccountForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(), Length(1, 20)])
    submit = SubmitField('提交')

    def validate_username(self, field):
        if field.data != current_user.username:
            raise ValidationError('错误的用户名')

betterme/blueprints/main.py
# -*- coding: utf-8 -*-
import os, random
from flask import render_template, flash, redirect, url_for, request, \
    current_app, Blueprint, abort, make_response, send_from_directory
from flask_login import current_user, login_required
from sqlalchemy.sql.expression import func

from betterme.decorators import permission_required, confirm_required
from betterme.forms.main import PostForm, TagForm, CommentForm
from betterme.models import User, Post, Photo, Comment, Tag, Collect, Notification,Follow
from betterme.extensions import db
from betterme.utils import rename_image, resize_image, flash_errors,redirect_back
from betterme.notifications import push_collect_notification, push_comment_notification


main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['POST_PER_PAGE']
        pagination = Post.query\
                .join(Follow, Follow.followed_id == Post.user_id)\
                .filter(Follow.follower_id == current_user.id)\
                .order_by(Post.timestamp.desc())\
                .paginate(page, per_page)
        posts = pagination.items
        photos = None
        tags = Tag.query.join(Tag.posts).group_by(Tag.id).order_by(func.count(Post.id).desc()).limit(8)
    else:
        photos = Photo.query.order_by(func.random()).limit(4)
        posts = None
        pagination = None
        tags = None
    return render_template('main/index.html', posts=posts, photos=photos, pagination=pagination, tags=tags)


@main_bp.route('/explore')
def explore():
    posts = Post.query.order_by(func.random()).limit(12) 
    return render_template('main/explore.html', posts=posts)

@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/uploads/images/<path:filename>/<int:user_id>')
def get_image(filename, user_id):
    user = User.query.get_or_404(user_id)
    user_path = os.path.join(current_app.config['UPLOAD_PATH'], user.name)
    return send_from_directory(user_path, filename)


@main_bp.route('/get/<int:post_id>')
def get_first_image(post_id):
    post = Post.query.get_or_404(post_id)
    photos = post.photos
    filename = photos[0].m_filename
    user_path = os.path.join(current_app.config['UPLOAD_PATH'], post.user.name)
    return send_from_directory(user_path, filename)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('UPLOAD')
def upload():
    form = PostForm()

    if request.method == 'POST' and 'file' in request.files:
        f = request.files['file']
        filename = rename_image(f.filename)
        path = os.path.join(
            current_app.config['UPLOAD_PATH'], current_user.name)
        if not os.path.exists(path):
            os.makedirs(path)
        f.save(os.path.join(
            current_app.config['UPLOAD_PATH'], current_user.name, filename))
        sfname = resize_image(f, filename, current_app.config['PHOTO_SIZE']['small'])
        mfname = resize_image(f, filename, current_app.config['PHOTO_SIZE']['medium'])

        p = Photo(
            filename=filename,
            s_filename=sfname,
            m_filename=mfname,
            user=current_user._get_current_object(),
        )
        db.session.add(p)
        db.session.commit()

    if form.validate_on_submit():
        body = form.body.data
        user = current_user._get_current_object()
        post = Post(body=body, user=user)
        db.session.add(post)
        unconnect_photos = Photo.query.filter_by(
            user=user).filter_by(connected=False).all()
        if unconnect_photos is not None:
            for p in unconnect_photos:
                p.connected = True
                p.user = user
                p.post = post
                db.session.add(p)
        db.session.commit()
        return redirect(url_for('.index'))
    return render_template('main/upload.html', form=form)


@main_bp.route('/post/<int:post_id>')
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MANAGE_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).order_by(
        Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items

    comment_form = CommentForm()
    post_form = PostForm()
    tag_form = TagForm()

    post_form.body.data = post.body
    return render_template('main/post.html', post=post, comment_form=comment_form,
                           post_form=post_form, tag_form=tag_form,
                           pagination=pagination, comments=comments)


@main_bp.route('/post/next/<int:post_id>')
def next_post(post_id):
    post = Post.query.get_or_404(post_id)
    next_post = Post.query.with_parent(post.user).filter(
        Post.id < post_id).order_by(Post.id.desc()).first()

    if next_post is None:
        flash('已经是最早的微博', 'info')
        return redirect(url_for('.show_post', post_id=post_id))
    return redirect(url_for('.show_post', post_id=next_post.id))


@main_bp.route('/post/prev/<int:post_id>')
def previous_post(post_id):
    post = Post.query.get_or_404(post_id)
    previous_post = Post.query.with_parent(post.user).filter(
        Post.id > post_id).order_by(Post.id.asc()).first()

    if previous_post is None:
        flash('已经是最新的微博', 'info')
        return redirect(url_for('.show_post', post_id=post_id))
    return redirect(url_for('.show_post', post_id=previous_post.id))


@main_bp.route('/post/<int:post_id>/edit_post', methods=['POST'])
@login_required
def edit_post(post_id):
    postform = PostForm()
    post = Post.query.get_or_404(post_id)

    if current_user != post.user:
        abort(403)
    if postform.validate_on_submit():
        post.body = postform.body.data
        db.session.commit()
        flash('微博已编辑', 'success')

    flash_errors(postform)
    return redirect(url_for('.show_post', post_id=post_id))


@main_bp.route('/post/<int:post_id>/comment/new', methods=['POST'])
@login_required
@permission_required('COMMENT')
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        body = form.body.data
        user = current_user._get_current_object()
        comment = Comment(body=body, user=user, post=post)

        replied_id = request.args.get('reply')
        if replied_id:
            comment.replied = Comment.query.get_or_404(replied_id)
        db.session.add(comment)
        db.session.commit()
        flash('评论已提交', 'success')
        if current_user != post.user:
            push_comment_notification(post.id, receiver=post.user, page=page)
    flash_errors(form)
    return redirect(url_for('.show_post', post_id=post_id, page=page))


@main_bp.route('/post/<int:post_id>/tag/new', methods=['POST'])
@login_required
def new_tag(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.user:
        abort(403)

    form = TagForm()
    if form.validate_on_submit():
        for name in form.tag.data.split():
            tag = Tag.query.filter_by(name=name).first()
            if tag is None:
                tag = Tag(name=name)
                db.session.add(tag)
                db.session.commit()
            if tag not in post.tags:
                post.tags.append(tag)
                db.session.commit()
            flash('标签已添加', 'success')

    flash_errors(form)
    return redirect(url_for('.show_post', post_id=post_id))


@main_bp.route('/set-comment/<int:post_id>', methods=['GET', 'POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.user:
        abort(403)

    if post.can_comment:
        post.can_comment = False
        flash('评论已关闭', 'info')
    else:
        post.can_comment = True
        flash('评论已开启','info')
    db.session.commit()
    return redirect(url_for('.show_post', post_id=post_id))


@main_bp.route('/reply/comment/<int:comment_id>')
@login_required
@permission_required('COMMENT')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(
        url_for('.show_post', post_id=comment.post_id, reply=comment_id,
                user=comment.user.name) + '#comment-form')


@main_bp.route('/delete/post/<int:post_id>', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('微博已删除', 'info')

    next_post = Post.query.with_parent(post.user).filter(
        Post.id < post_id).order_by(Post.id.desc()).first()
    if next_post is None:
        next_post = Post.query.with_parent(post.user).filter(
            Post.id > post_id).order_by(Post.id.asc()).first()
        if next_post is None:
            return redirect(url_for('user.index', username=post.user.username))
        return redirect(url_for('.show_post', post_id=next_post.id))
    return redirect(url_for('.show_post', post_id=next_post.id))


@main_bp.route('/delete/comment/<int:comment_id>', methods=['POST'])
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.post.user and current_user != comment.user:
        abort(403)

    db.session.delete(comment)
    db.session.commit()
    flash('评论已删除', 'info')
    return redirect(url_for('.show_post', post_id=comment.post_id))


@main_bp.route('/tag/<int:tag_id>', defaults={'order': 'by_time'})
@main_bp.route('/tag/<int:tag_id>/<order>')
def show_tag(tag_id, order):
    tag = Tag.query.get_or_404(tag_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MANAGE_COMMENT_PER_PAGE']
    order_rule = 'time'

betterme/templates/user/_header.html
{% from 'bootstrap/nav.html' import render_nav_item %}
{% from 'macros.html' import follow_button with context %}

    <div class="card">
        <div class="card-body">
            <div class="row">
            <div class="col-md-3">
                <img class="img-fluid rounded" src="{{ url_for('main.get_avatar', filename=user.l_avatar) }}">
            </div>
            <div class="col-md-9">
                <h1>{{ user.name }}
                    <small class="text-muted">{{ user.username }}</small>
                </h1>
                {% if user.bio %}<p>{{ user.bio }}</p>{% endif %}
                <p>
                    {% if user.website %}
                    <span class="oi oi-link-intact"></span>
                    <a href="{{ user.website }}" target="_blank">{{ user.website|truncate(30) }}</a>&nbsp;&nbsp;
                    {% endif %}
                    {% if user.location %}
                    <span class="oi oi-map-marker"></span>
                    <a href="https://www.google.com/maps?q={{ user.location }}"
                        target="_blank">{{ user.location|truncate(30) }}</a>&nbsp;&nbsp;
                    {% endif %}
                    <span class="oi oi-calendar"></span>
                    Joined {{ moment(user.member_since).format('LL') }}
                </p>
                {{follow_button(user)}}
            </div>
            </div>
        </div>
    </div>

<div class="user-nav">
    <ul class="nav nav-tabs">
        {{ render_nav_item('user.index', '微博', user.photos|length, username=user.username) }}
        {{ render_nav_item('user.show_collections', '收藏', user.collections|length, username=user.username) }}
        {{ render_nav_item('user.show_followers', '粉丝', user.followers.count()-1 , username=user.username) }}
        {{ render_nav_item('user.show_following', '关注', user.following.count()-1 , username=user.username) }}
    </ul>
</div>

betterme/templates/user/collections.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import post_card with context %}

{% block title %}收藏{% endblock %}

{% block content %}
{% include 'user/_header.html' %}
<div class="row">
    <div class="col-md-12">
        {% if collects %}
        <div class="card-columns">
            {% for collect in collects %}
            {{ post_card(collect.collected) }}
            {% endfor %}
        </div>
        {% else %}
        <div class="tip text-center">
            <h3>没有微博</h3>
            <a class="btn btn-link" href="{{ url_for('main.explore') }}">发现</a>
        </div>
        {% endif %}

{% if posts %}
<div class="page-footer">
    {{ render_pagination(pagination, align='right') }}
</div>
{% endif %}
    </div>
</div>
{% endblock %}

betterme/templates/user/followers.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}粉丝{% endblock %}

{% block content %}
{% include 'user/_header.html' %}
<div class="row">
    <div class="col-md-12">
        {% if follows|length != 1 %}
        <div class="card-columns">
            {% for follow in follows %}
                {% if follow.follower != user %}
                    {{ user_card(follow.follower) }}
                {% endif %}
            {% endfor %}
        </div>
        {% else %}
        <div class="tip text-center">
            <h3>No Follower.</h3>
            <a class="btn btn-link" href="{{ url_for('main.explore') }}">发现</a>
        </div>
        {% endif %}

{% if follows %}
<div class="page-footer">
    {{ render_pagination(pagination, align='right') }}
</div>
{% endif %}
    </div>
</div>
{% endblock %}

betterme/templates/user/following.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}关注{% endblock %}

{% block content %}
{% include 'user/_header.html' %}
<div class="row">
    <div class="col-md-12">
        {% if follows|length != 1 %}
        <div class="card-columns">
            {% for follow in follows %}
                {% if follow.followed != user %}
                    {{ user_card(follow.followed) }}
                {% endif %}
            {% endfor %}
        </div>
        {% else %}
        <div class="tip text-center">
            <h3>No Following.</h3>
            <a class="btn btn-link" href="{{ url_for('main.explore') }}">发现</a>
        </div>
        {% endif %}

{% if follows %}
<div class="page-footer">
    {{ render_pagination(pagination, align='right') }}
</div>
{% endif %}
    </div>
</div>
{% endblock %}

betterme/templates/user/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import post_card, follow_button with context %}

{% block title %}{{ user.name }}{% endblock %}

{% block content %}
{% include 'user/_header.html' %}
<div class="row">
    <div class="col-md-12">
        {% if posts %}
        <div class="card-columns">
            {% for post in posts %}
            {{ post_card(post) }}
            {% endfor %}
        </div>
        {% else %}
        <div class="tip text-center">
            <h3>没有微博</h3>
            {% if user == current_user %}
            <a class="btn btn-link" href="{{ url_for('main.upload') }}">发布新微博</a>
            {% else %}
            <a class="btn btn-link" href="{{ url_for('main.explore') }}">发现</a>
            {% endif %}
        </div>
        {% endif %}

{% if posts %}
<div class="page-footer">
    {{ render_pagination(pagination, align='right') }}
</div>
{% endif %}
</div>
{% endblock %}