betterme/forms/main.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo, Optional
from wtforms import ValidationError

from betterme.models import User, Post, Photo

class PostForm(FlaskForm):
    body = StringField('微博内容', validators=[DataRequired(), Length(1,144)])
    submit = SubmitField('发布')


class TagForm(FlaskForm):
    tag = StringField('添加标签（空格分隔）', validators=[Optional(), Length(0, 64)])
    submit = SubmitField('添加')


class CommentForm(FlaskForm):
    body = TextAreaField('', validators=[DataRequired()])
    submit = SubmitField('发布')

betterme/blueprints/ajax.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, redirect, url_for, request, \
    current_app, Blueprint, abort, make_response, send_from_directory, jsonify
from flask_login import current_user, login_required

from betterme.decorators import permission_required, confirm_required
from betterme.forms.main import PostForm, TagForm, CommentForm
from betterme.models import User, Post, Photo, Comment, Tag, Notification
from betterme.extensions import db
from betterme.utils import rename_image, resize_image, flash_errors

ajax_bp = Blueprint('ajax', __name__)

@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)

@ajax_bp.route('/count-follower/<int:user_id>')
def count_follower(user_id):
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1
    return jsonify(count=count)

@ajax_bp.route('/follow/<username>', methods=['POST'])
def follow(username):
    if not current_user.is_authenticated:
        return jsonify(message='请先登录'), 403
    if not current_user.confirmed:
        return jsonify(message='请先完成账户确认'), 400
    if not current_user.can('FOLLOW'):
        return jsonify(message='您没有该权限'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_follow(user):
        return jsonify(message='亲，已经关注了'), 400

    current_user.follow(user)
    return jsonify(message='关注成功')


@ajax_bp.route('/unfollow/<username>', methods=['POST'])
def unfollow(username):
    if not current_user.is_authenticated:
        return jsonify(message='请先登陆'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_follow(user):
        return jsonify(message='还没关注'), 400

    current_user.unfollow(user)
    return jsonify(message='取消关注')

@ajax_bp.route('/notification-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='请先登录'), 403
    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)

betterme/blueprints/auth.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login

from betterme.emails import send_confirm_email, send_reset_password_email
from betterme.extensions import db
from sqlalchemy.sql.expression import func
from betterme.forms.auth import LoginForm, RegisterForm, ForgetPasswordForm, ResetPasswordForm
from betterme.models import User, Photo
from betterme.configs import Operations
from betterme.utils import generate_token, validate_token, redirect_back
auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    photos = Photo.query.order_by(func.random()).limit(4)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user, form.remember_me.data)
            flash('Login success.', 'info')
            return redirect_back()
        flash('Invalid email or password.', 'warning')
    return render_template('auth/login.html', form=form, photos=photos)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout Success', 'info')
    return redirect(url_for('main.index'))

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    photos = Photo.query.order_by(func.random()).limit(4)
    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        token = generate_token(user=user, operation='confirm')
        send_confirm_email(user=user, token=token)
        flash('Confirm email sent, check your inbox.', 'info')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form, photos=photos)

@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return rediect(url_for('main.index'))

    if validate_token(user=current_user, token=token, operation=Operations.CONFIRM):
        flash('邮箱已验证', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('验证连接非法或已过期', 'danger')
        return redirect(url_for('.resend_confirm_email'))

@auth_bp.route('/resend-confirm-email')
@login_required
def resend_confirm_email():
    if current_user.confirmed:
        return redirect(url_for('main.index'))
    token = generate_token(user=current_user, operation=Operations.CONFIRM)
    send_confirm_email(user=current_user, token=token)
    flash('新的验证连接已发送，请检查邮箱', 'info')
    return redirect(url_for('main.index'))

@auth_bp.route('forget-password', methods=['GET', 'POST'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    
    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            senf_reset_password_email(user=user, token=token)
            flash('验证连接已发送，请检查邮箱', 'info')
            return redirect(url_for('.login'))
        flash('用户不存在', 'warning')
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)

@auth_bp.route('reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    
    form = RegisterForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash('用户不存在', 'warning')
            return redirect(url_for('main.index'))
        elif validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD, new_password=form.password.data):
            flash('密码已修改', 'success')
            return redirect(url_for('.login'))
        else:
            flash('链接非法或已过期', 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)

betterme/blueprints/main.py
# -*- coding: utf-8 -*-
import os, random
from flask import render_template, flash, redirect, url_for, request, \
    current_app, Blueprint, abort, make_response, send_from_directory
from flask_login import current_user, login_required
from sqlalchemy.sql.expression import func

from betterme.decorators import permission_required, confirm_required
from betterme.forms.main import PostForm, TagForm, CommentForm
from betterme.models import User, Post, Photo, Comment, Tag, Collect, Notification,Follow
from betterme.extensions import db
from betterme.utils import rename_image, resize_image, flash_errors,redirect_back
from betterme.notifications import push_collect_notification, push_comment_notification


main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['POST_PER_PAGE']
        pagination = Post.query\
                .join(Follow, Follow.followed_id == Post.user_id)\
                .filter(Follow.follower_id == current_user.id)\
                .order_by(Post.timestamp.desc())\
                .paginate(page, per_page)
        posts = pagination.items
        photos = None
        tags = Tag.query.join(Tag.posts).group_by(Tag.id).order_by(func.count(Post.id).desc()).limit(8)
    else:
        photos = Photo.query.order_by(func.random()).limit(4)
        posts = None
        pagination = None
        tags = None
    return render_template('main/index.html', posts=posts, photos=photos, pagination=pagination, tags=tags)


@main_bp.route('/explore')
def explore():
    posts = Post.query.order_by(func.random()).limit(12) 
    return render_template('main/explore.html', posts=posts)

@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/uploads/images/<path:filename>/<int:user_id>')
def get_image(filename, user_id):
    user = User.query.get_or_404(user_id)
    user_path = os.path.join(current_app.config['UPLOAD_PATH'], user.name)
    return send_from_directory(user_path, filename)


@main_bp.route('/get/<int:post_id>')
def get_first_image(post_id):
    post = Post.query.get_or_404(post_id)
    photos = post.photos
    filename = photos[0].m_filename
    user_path = os.path.join(current_app.config['UPLOAD_PATH'], post.user.name)
    return send_from_directory(user_path, filename)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('UPLOAD')
def upload():
    form = PostForm()

    if request.method == 'POST' and 'file' in request.files:
        f = request.files['file']
        filename = rename_image(f.filename)
        path = os.path.join(
            current_app.config['UPLOAD_PATH'], current_user.name)
        if not os.path.exists(path):
            os.makedirs(path)
        f.save(os.path.join(
            current_app.config['UPLOAD_PATH'], current_user.name, filename))
        sfname = resize_image(f, filename, current_app.config['PHOTO_SIZE']['small'])
        mfname = resize_image(f, filename, current_app.config['PHOTO_SIZE']['medium'])

        p = Photo(
            filename=filename,
            s_filename=sfname,
            m_filename=mfname,
            user=current_user._get_current_object(),
        )
        db.session.add(p)
        db.session.commit()

    if form.validate_on_submit():
        body = form.body.data
        user = current_user._get_current_object()
        post = Post(body=body, user=user)
        db.session.add(post)
        unconnect_photos = Photo.query.filter_by(
            user=user).filter_by(connected=False).all()
        if unconnect_photos is not None:
            for p in unconnect_photos:
                p.connected = True
                p.user = user
                p.post = post
                db.session.add(p)
        db.session.commit()
        return redirect(url_for('.index'))
    return render_template('main/upload.html', form=form)


@main_bp.route('/post/<int:post_id>')
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MANAGE_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).order_by(
        Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items

    comment_form = CommentForm()
    post_form = PostForm()
    tag_form = TagForm()

    post_form.body.data = post.body
    return render_template('main/post.html', post=post, comment_form=comment_form,
                           post_form=post_form, tag_form=tag_form,
                           pagination=pagination, comments=comments)


@main_bp.route('/post/next/<int:post_id>')
def next_post(post_id):
    post = Post.query.get_or_404(post_id)
    next_post = Post.query.with_parent(post.user).filter(
        Post.id < post_id).order_by(Post.id.desc()).first()

    if next_post is None:
        flash('已经是最早的微博', 'info')
        return redirect(url_for('.show_post', post_id=post_id))
    return redirect(url_for('.show_post', post_id=next_post.id))


@main_bp.route('/post/prev/<int:post_id>')
def previous_post(post_id):
    post = Post.query.get_or_404(post_id)
    previous_post = Post.query.with_parent(post.user).filter(
        Post.id > post_id).order_by(Post.id.asc()).first()

    if previous_post is None:
        flash('已经是最新的微博', 'info')
        return redirect(url_for('.show_post', post_id=post_id))
    return redirect(url_for('.show_post', post_id=previous_post.id))


@main_bp.route('/post/<int:post_id>/edit_post', methods=['POST'])
@login_required
def edit_post(post_id):
    postform = PostForm()
    post = Post.query.get_or_404(post_id)

    if current_user != post.user:
        abort(403)
    if postform.validate_on_submit():
        post.body = postform.body.data
        db.session.commit()
        flash('微博已编辑', 'success')

    flash_errors(postform)
    return redirect(url_for('.show_post', post_id=post_id))


@main_bp.route('/post/<int:post_id>/comment/new', methods=['POST'])
@login_required
@permission_required('COMMENT')
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        body = form.body.data
        user = current_user._get_current_object()
        comment = Comment(body=body, user=user, post=post)

        replied_id = request.args.get('reply')
        if replied_id:
            comment.replied = Comment.query.get_or_404(replied_id)
        db.session.add(comment)
        db.session.commit()
        flash('评论已提交', 'success')
        if current_user != post.user:
            push_comment_notification(post.id, receiver=post.user, page=page)
    flash_errors(form)
    return redirect(url_for('.show_post', post_id=post_id, page=page))


@main_bp.route('/post/<int:post_id>/tag/new', methods=['POST'])
@login_required
def new_tag(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.user:
        abort(403)

    form = TagForm()
    if form.validate_on_submit():
        for name in form.tag.data.split():
            tag = Tag.query.filter_by(name=name).first()
            if tag is None:
                tag = Tag(name=name)
                db.session.add(tag)
                db.session.commit()
            if tag not in post.tags:
                post.tags.append(tag)
                db.session.commit()
            flash('标签已添加', 'success')

    flash_errors(form)
    return redirect(url_for('.show_post', post_id=post_id))


@main_bp.route('/set-comment/<int:post_id>', methods=['GET', 'POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.user:
        abort(403)

    if post.can_comment:
        post.can_comment = False
        flash('评论已关闭', 'info')
    else:
        post.can_comment = True
        flash('评论已开启','info')
    db.session.commit()
    return redirect(url_for('.show_post', post_id=post_id))


@main_bp.route('/reply/comment/<int:comment_id>')
@login_required
@permission_required('COMMENT')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(
        url_for('.show_post', post_id=comment.post_id, reply=comment_id,
                user=comment.user.name) + '#comment-form')


@main_bp.route('/delete/post/<int:post_id>', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('微博已删除', 'info')

    next_post = Post.query.with_parent(post.user).filter(
        Post.id < post_id).order_by(Post.id.desc()).first()
    if next_post is None:
        next_post = Post.query.with_parent(post.user).filter(
            Post.id > post_id).order_by(Post.id.asc()).first()
        if next_post is None:
            return redirect(url_for('user.index', username=post.user.username))
        return redirect(url_for('.show_post', post_id=next_post.id))
    return redirect(url_for('.show_post', post_id=next_post.id))


@main_bp.route('/delete/comment/<int:comment_id>', methods=['POST'])
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.post.user and current_user != comment.user:
        abort(403)

    db.session.delete(comment)
    db.session.commit()
    flash('评论已删除', 'info')
    return redirect(url_for('.show_post', post_id=comment.post_id))


@main_bp.route('/tag/<int:tag_id>', defaults={'order': 'by_time'})
@main_bp.route('/tag/<int:tag_id>/<order>')
def show_tag(tag_id, order):
    tag = Tag.query.get_or_404(tag_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MANAGE_COMMENT_PER_PAGE']
    order_rule = 'time'

betterme/templates/main/_comments.html
<div class="comments" id="comments">
    <h3>{{ post.comments|length }} 条评论
        <small>
            <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1) }}#comment-form">最新</a>
        </small>
        {% if current_user == post.user %}
            <a class="btn btn-xs btn-link float-right" href="{{ url_for('.set_comment', post_id=post.id) }}">
                {% if post.can_comment %}关闭{% else %}开启{% endif %} 评论
            </a>
        {% endif %}
    </h3>
    <hr>
    {% if comments %}
        {% for comment in comments %}
            <div class="comment">
                <div class="comment-thumbnail">
                    <a href="{{ url_for('user.index', username=comment.user.username) }}">
                        <img class="rounded img-fluid avatar-s profile-popover"
                             data-href="{{ url_for('ajax.get_profile', user_id=comment.user.id) }}"
                             src="{{ url_for('main.get_avatar', filename=comment.user.s_avatar) }}">
                    </a>
                </div>
                <div class="comment-body">
                    <h6>
                        <a class="profile-popover"
                        data-href="{{ url_for('ajax.get_profile', user_id=comment.user.id) }}"
                        href="{{ url_for('user.index', username=comment.user.username) }}">
                            {{ comment.user.name }}
                        </a>
                        {% if comment.user == post.user %}
                            <span class="badge badge-light">用户</span>
                        {% endif %}
                        <small data-toggle="tooltip" data-placement="top" data-timestamp="{{ comment.timestamp }}"
                               data-delay="500">
                            {{ moment(comment.timestamp).fromNow(refresh=True) }}
                        </small>
                        {% if current_user.is_authenticated %}
                            <span class="float-right">
                            <span class="dropdown">
                                <button class="btn btn-sm btn-light" type="button" id="dropdownMenuButton"
                                        data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">
                                <span class="oi oi-ellipses"></span>
                                </button>
                                <span class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                {% if current_user != comment.user %}
                                    <a class="dropdown-item btn"
                                       href="{{ url_for('.reply_comment', comment_id=comment.id) }}">
                                    <span class="oi oi-comment-square"></span> 回复
                                </a>
                                {% endif %}
                                    {% if current_user == comment.user or current_user == post.user %}
                                        <a class="dropdown-item" data-toggle="modal" href="#!"
                                           data-href="{{ url_for('.delete_comment', comment_id=comment.id) }}"
                                           data-target="#confirm-delete">
                                        <span class="oi oi-trash" aria-hidden="true"></span> 删除
                                      </a>
                                    {% endif %}
                                </span>
                                </span>
                            </span>
                        {% endif %}
                    </h6>
                    <p>
                        {% if comment.replied %}
                            Reply
                            <a href="{{ url_for('user.index', username=comment.replied.user.username) }}">{{ comment.replied.user.name }}</a>
                            :
                        {%- endif -%}
                        {{ comment.body }}
                    </p>
                </div>
            </div>
            <hr>
        {% endfor %}
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% else %}
        <p class="tip">目前还没有评论</p>
    {% endif %}

    {% if post.can_comment %}
        {% if current_user.is_authenticated %}
            {% if current_user.can('COMMENT') %}
                {% if request.args.get('reply') %}
                    <div class="alert alert-dark">
                        向 {{ request.args.get('user') }} 回复:
                        <a class="float-right" href="{{ url_for('.show_post', post_id=post.id) }}">取消</a>
                    </div>
                {% endif %}
                <div class="comment-form-area">
                    <div class="comment-form-thumbnail">
                        <img class="rounded img-fluid avatar-s"
                             src="{{ url_for('main.get_avatar', filename=current_user.m_avatar) }}">
                    </div>
                    <div class="comment-form" id="comment-form">
                        {{ render_form(comment_form, action=url_for('.new_comment', post_id=post.id, page=pagination.pages),
                        extra_classes="text-right") }}
                    </div>
                </div>
            {% else %}
                <p class="tip">
                    权限错误
                </p>
            {% endif %}
        {% else %}
            <p class="tip">
                <a href="{{ url_for('auth.login') }}">登陆</a>
                or
                <a href="{{ url_for('auth.register') }}">注册</a>以评论
            </p>
        {% endif %}
    {% else %}
        <p class="tip">
            评论已关闭
        </p>
    {% endif %}
</div>

betterme/templates/main/collectors.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}收藏用户{% endblock %}

{% block content %}
    <div class="page-header">
        <div class="row">
            <div class="col-md-12">
                <a class="btn btn-default btn-sm" href="{{ url_for('main.show_post', post_id=post.id) }}">
                    <span class="oi oi-arrow-left" aria-hidden="true"></span> 返回
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>{{ post.collectors|length }} 位收藏用户</h3>
            {% for collect in collects %}
                {{ user_card(user=collect.collector) }}
            {% endfor %}
        </div>
    </div>
    {% if collections %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock %}

betterme/templates/main/explore.html
{% extends 'base.html' %}
{% from 'macros.html' import post_card with context %}
{% block title %}发现{% endblock %}

{% block content %}
<div class="row">
        <div class="col-md-11">
        <div class="card-columns">
        {% for post in posts %}
                {{ post_card(post) }}
        {% endfor %}
        </div>
        </div>
    </div>
{% endblock %}

betterme/templates/main/index.html
{% extends 'base.html' %}
{% from 'macros.html' import post_card, user_card with context %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}主页{% endblock %}

{% block content %}
{% if current_user.is_authenticated %}
<div class="row">
    <div class="col-md-8">
        {% if posts %}
        <div class="card-columns">
            {% for post in posts %}
            {{ post_card(post) }}
            {% endfor %}
        </div>
        {% else %}
        <div class="tip text-center">
            <h3>没有微博</h3>
            去<a class="btn btn-link" href="{{ url_for('main.explore') }}">发现</a>
        </div>
        {% endif %}
        {% if posts %}
      <div class="page-footer">
          {{ render_pagination(pagination, align='right') }}
      </div>
      {% endif %}
    </div>
    <div class="col-md-4">
        {{ user_card(current_user) }}
        <div class="card">
            <div class="card-header">
              热门标签
            </div>
            <ul class="list-group list-group-flush">
              {% for tag in tags %}
              <a href="{{ url_for('main.show_tag', tag_id=tag.id) }}">
              <li class="list-group-item">{{tag.name}} {{tag.posts|count}} </li> </a>
              {% endfor %}
            </ul>
      </div>
    </div>
</div>
{% else %}
<div class="jumbotron">
  <div class="row">
    <div class="col-md-8">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner">
          {% for photo in photos %}
          <div class="carousel-item {% if loop.index == 1 %} active {% endif %}" style="height: 400px;">
              <img src="{{ url_for('main.get_image', filename=photo.filename, user_id=photo.user.id) }}" class="d-block w-100" alt="...">
          </div>
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only"></span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only"></span>
        </a>
      </div>
    </div>
    <div class="col-md-4 align-self-center">
      <h1>BetterMe</h1>
      <p>Remember every wonderful moment to be a better man.</p>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

betterme/templates/main/profile_popup.html
<div class="popup-card">
    <img class="rounded img-fluid avatar-s popup-avatar" src="{{ url_for('main.get_avatar', filename=user.m_avatar) }}">
    <div class="popup-profile">
        <h6>{{ user.name }}</h6>
        <p class="text-muted">{{ user.username }}</p>
    </div>
    <p class="card-text">
        <a href="{{ url_for('user.index', username=user.username) }}">
            <strong>{{ user.posts|length }}</strong> 微博
        </a>&nbsp;
        <a href="{{ url_for('user.show_followers', username=user.username) }}">
                <strong id="followers-count-{{ user.id }}"
                        data-href="{{ url_for('ajax.count_follower', user_id=user.id) }}">
                    {{ user.followers.count() - 1 }}
                </strong> 粉丝
            </a>
    </p>
    <a href="{{ url_for('user.index', username=user.username) }}" class="btn btn-light btn-sm">主页</a>
    {% if current_user.is_authenticated %}
    {% if user != current_user %}
        <button data-id="{{ user.id }}"
                data-href="{{ url_for('ajax.unfollow', username=user.username) }}"
                class="{% if not current_user.is_follow(user) %}hide{% endif %} btn btn-dark btn-sm unfollow-btn">
            取消关注
        </button>
        <button data-id="{{ user.id }}"
                data-href="{{ url_for('ajax.follow', username=user.username) }}"
                class="{% if current_user.is_follow(user) %}hide{% endif %} btn btn-primary btn-sm follow-btn">
            关注
        </button>
    {% endif %}
{% else %}
    <form class="inline" method="post"
          action="{{ url_for('user.follow', username=user.username) }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <button type="submit" class="btn btn-primary btn-sm">关注</button>
    </form>
{% endif %}
</div>

betterme/templates/main/search.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import post_card, user_card with context %}

{% block title %}搜索: {{ t }}{% endblock %}

{% block content %}
<div class="page-header">
    <h1>搜索: {{ t }}</h1>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="nav nav-pills flex-column" role="tablist" aria-orientation="vertical">
            <div>
                <a class="nav-item nav-link {% if category == 'post' %}active{% endif %}"
                    href="{{ url_for('.search', t=t, category='post') }}">微博 <span class="badge">{{posts}}</span></a>
            </div>
            <div>
                <a class="nav-item nav-link {% if category == 'user' %}active{% endif %}"
                    href="{{ url_for('.search', t=t, category='user') }}">用户 <span class="badge">{{users}}</span></a>
            </div>
            <div>
                <a class="nav-item nav-link {% if category == 'tag' %}active{% endif %}"
                    href="{{ url_for('.search', t=t, category='tag') }}">标签 <span class="badge">{{tags}}</span></a>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        {% if results %}
        <h5>{{ results|length }} 条结果</h5>
        <div class="card-columns">
            {% for item in results %}
            {% if category == 'post' %}
            {{ post_card(item) }}
            {% elif category == 'user' %}
            {{ user_card(item) }}
            {% else %}
            <a class="badge badge-light" href="{{ url_for('.show_tag', tag_id=item.id) }}">
                {{ item.name }} {{ item.posts|length }}
            </a>
            {% endif %}
            {% endfor %}
        </div>
        {% else %}
        <h5 class="tip">没有匹配结果</h5>
        {% endif %}
    </div>
</div>
{% if results %}
<div class="page-footer">
    {{ render_pagination(pagination, align='right') }}
</div>
{% endif %}
{% endblock %}