betterme/blueprints/ajax.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, redirect, url_for, request, \
    current_app, Blueprint, abort, make_response, send_from_directory, jsonify
from flask_login import current_user, login_required

from betterme.decorators import permission_required, confirm_required
from betterme.forms.main import PostForm, TagForm, CommentForm
from betterme.models import User, Post, Photo, Comment, Tag, Notification
from betterme.extensions import db
from betterme.utils import rename_image, resize_image, flash_errors

ajax_bp = Blueprint('ajax', __name__)

@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)

@ajax_bp.route('/count-follower/<int:user_id>')
def count_follower(user_id):
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1
    return jsonify(count=count)

@ajax_bp.route('/follow/<username>', methods=['POST'])
def follow(username):
    if not current_user.is_authenticated:
        return jsonify(message='请先登录'), 403
    if not current_user.confirmed:
        return jsonify(message='请先完成账户确认'), 400
    if not current_user.can('FOLLOW'):
        return jsonify(message='您没有该权限'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_follow(user):
        return jsonify(message='亲，已经关注了'), 400

    current_user.follow(user)
    return jsonify(message='关注成功')


@ajax_bp.route('/unfollow/<username>', methods=['POST'])
def unfollow(username):
    if not current_user.is_authenticated:
        return jsonify(message='请先登陆'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_follow(user):
        return jsonify(message='还没关注'), 400

    current_user.unfollow(user)
    return jsonify(message='取消关注')

@ajax_bp.route('/notification-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='请先登录'), 403
    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)

betterme/blueprints/auth.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login

from betterme.emails import send_confirm_email, send_reset_password_email
from betterme.extensions import db
from sqlalchemy.sql.expression import func
from betterme.forms.auth import LoginForm, RegisterForm, ForgetPasswordForm, ResetPasswordForm
from betterme.models import User, Photo
from betterme.configs import Operations
from betterme.utils import generate_token, validate_token, redirect_back
auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    photos = Photo.query.order_by(func.random()).limit(4)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user, form.remember_me.data)
            flash('Login success.', 'info')
            return redirect_back()
        flash('Invalid email or password.', 'warning')
    return render_template('auth/login.html', form=form, photos=photos)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout Success', 'info')
    return redirect(url_for('main.index'))

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    photos = Photo.query.order_by(func.random()).limit(4)
    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        token = generate_token(user=user, operation='confirm')
        send_confirm_email(user=user, token=token)
        flash('Confirm email sent, check your inbox.', 'info')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form, photos=photos)

@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return rediect(url_for('main.index'))

    if validate_token(user=current_user, token=token, operation=Operations.CONFIRM):
        flash('邮箱已验证', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('验证连接非法或已过期', 'danger')
        return redirect(url_for('.resend_confirm_email'))

@auth_bp.route('/resend-confirm-email')
@login_required
def resend_confirm_email():
    if current_user.confirmed:
        return redirect(url_for('main.index'))
    token = generate_token(user=current_user, operation=Operations.CONFIRM)
    send_confirm_email(user=current_user, token=token)
    flash('新的验证连接已发送，请检查邮箱', 'info')
    return redirect(url_for('main.index'))

@auth_bp.route('forget-password', methods=['GET', 'POST'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    
    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            senf_reset_password_email(user=user, token=token)
            flash('验证连接已发送，请检查邮箱', 'info')
            return redirect(url_for('.login'))
        flash('用户不存在', 'warning')
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)

@auth_bp.route('reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    
    form = RegisterForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash('用户不存在', 'warning')
            return redirect(url_for('main.index'))
        elif validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD, new_password=form.password.data):
            flash('密码已修改', 'success')
            return redirect(url_for('.login'))
        else:
            flash('链接非法或已过期', 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)

betterme/blueprints/main.py
# -*- coding: utf-8 -*-
import os, random
from flask import render_template, flash, redirect, url_for, request, \
    current_app, Blueprint, abort, make_response, send_from_directory
from flask_login import current_user, login_required
from sqlalchemy.sql.expression import func

from betterme.decorators import permission_required, confirm_required
from betterme.forms.main import PostForm, TagForm, CommentForm
from betterme.models import User, Post, Photo, Comment, Tag, Collect, Notification,Follow
from betterme.extensions import db
from betterme.utils import rename_image, resize_image, flash_errors,redirect_back
from betterme.notifications import push_collect_notification, push_comment_notification


main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['POST_PER_PAGE']
        pagination = Post.query\
                .join(Follow, Follow.followed_id == Post.user_id)\
                .filter(Follow.follower_id == current_user.id)\
                .order_by(Post.timestamp.desc())\
                .paginate(page, per_page)
        posts = pagination.items
        photos = None
        tags = Tag.query.join(Tag.posts).group_by(Tag.id).order_by(func.count(Post.id).desc()).limit(8)
    else:
        photos = Photo.query.order_by(func.random()).limit(4)
        posts = None
        pagination = None
        tags = None
    return render_template('main/index.html', posts=posts, photos=photos, pagination=pagination, tags=tags)


@main_bp.route('/explore')
def explore():
    posts = Post.query.order_by(func.random()).limit(12) 
    return render_template('main/explore.html', posts=posts)

@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/uploads/images/<path:filename>/<int:user_id>')
def get_image(filename, user_id):
    user = User.query.get_or_404(user_id)
    user_path = os.path.join(current_app.config['UPLOAD_PATH'], user.name)
    return send_from_directory(user_path, filename)


@main_bp.route('/get/<int:post_id>')
def get_first_image(post_id):
    post = Post.query.get_or_404(post_id)
    photos = post.photos
    filename = photos[0].m_filename
    user_path = os.path.join(current_app.config['UPLOAD_PATH'], post.user.name)
    return send_from_directory(user_path, filename)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('UPLOAD')
def upload():
    form = PostForm()

    if request.method == 'POST' and 'file' in request.files:
        f = request.files['file']
        filename = rename_image(f.filename)
        path = os.path.join(
            current_app.config['UPLOAD_PATH'], current_user.name)
        if not os.path.exists(path):
            os.makedirs(path)
        f.save(os.path.join(
            current_app.config['UPLOAD_PATH'], current_user.name, filename))
        sfname = resize_image(f, filename, current_app.config['PHOTO_SIZE']['small'])
        mfname = resize_image(f, filename, current_app.config['PHOTO_SIZE']['medium'])

        p = Photo(
            filename=filename,
            s_filename=sfname,
            m_filename=mfname,
            user=current_user._get_current_object(),
        )
        db.session.add(p)
        db.session.commit()

    if form.validate_on_submit():
        body = form.body.data
        user = current_user._get_current_object()
        post = Post(body=body, user=user)
        db.session.add(post)
        unconnect_photos = Photo.query.filter_by(
            user=user).filter_by(connected=False).all()
        if unconnect_photos is not None:
            for p in unconnect_photos:
                p.connected = True
                p.user = user
                p.post = post
                db.session.add(p)
        db.session.commit()
        return redirect(url_for('.index'))
    return render_template('main/upload.html', form=form)


@main_bp.route('/post/<int:post_id>')
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MANAGE_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).order_by(
        Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items

    comment_form = CommentForm()
    post_form = PostForm()
    tag_form = TagForm()

    post_form.body.data = post.body
    return render_template('main/post.html', post=post, comment_form=comment_form,
                           post_form=post_form, tag_form=tag_form,
                           pagination=pagination, comments=comments)


@main_bp.route('/post/next/<int:post_id>')
def next_post(post_id):
    post = Post.query.get_or_404(post_id)
    next_post = Post.query.with_parent(post.user).filter(
        Post.id < post_id).order_by(Post.id.desc()).first()

    if next_post is None:
        flash('已经是最早的微博', 'info')
        return redirect(url_for('.show_post', post_id=post_id))
    return redirect(url_for('.show_post', post_id=next_post.id))


@main_bp.route('/post/prev/<int:post_id>')
def previous_post(post_id):
    post = Post.query.get_or_404(post_id)
    previous_post = Post.query.with_parent(post.user).filter(
        Post.id > post_id).order_by(Post.id.asc()).first()

    if previous_post is None:
        flash('已经是最新的微博', 'info')
        return redirect(url_for('.show_post', post_id=post_id))
    return redirect(url_for('.show_post', post_id=previous_post.id))


@main_bp.route('/post/<int:post_id>/edit_post', methods=['POST'])
@login_required
def edit_post(post_id):
    postform = PostForm()
    post = Post.query.get_or_404(post_id)

    if current_user != post.user:
        abort(403)
    if postform.validate_on_submit():
        post.body = postform.body.data
        db.session.commit()
        flash('微博已编辑', 'success')

    flash_errors(postform)
    return redirect(url_for('.show_post', post_id=post_id))


@main_bp.route('/post/<int:post_id>/comment/new', methods=['POST'])
@login_required
@permission_required('COMMENT')
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        body = form.body.data
        user = current_user._get_current_object()
        comment = Comment(body=body, user=user, post=post)

        replied_id = request.args.get('reply')
        if replied_id:
            comment.replied = Comment.query.get_or_404(replied_id)
        db.session.add(comment)
        db.session.commit()
        flash('评论已提交', 'success')
        if current_user != post.user:
            push_comment_notification(post.id, receiver=post.user, page=page)
    flash_errors(form)
    return redirect(url_for('.show_post', post_id=post_id, page=page))


@main_bp.route('/post/<int:post_id>/tag/new', methods=['POST'])
@login_required
def new_tag(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.user:
        abort(403)

    form = TagForm()
    if form.validate_on_submit():
        for name in form.tag.data.split():
            tag = Tag.query.filter_by(name=name).first()
            if tag is None:
                tag = Tag(name=name)
                db.session.add(tag)
                db.session.commit()
            if tag not in post.tags:
                post.tags.append(tag)
                db.session.commit()
            flash('标签已添加', 'success')

    flash_errors(form)
    return redirect(url_for('.show_post', post_id=post_id))


@main_bp.route('/set-comment/<int:post_id>', methods=['GET', 'POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.user:
        abort(403)

    if post.can_comment:
        post.can_comment = False
        flash('评论已关闭', 'info')
    else:
        post.can_comment = True
        flash('评论已开启','info')
    db.session.commit()
    return redirect(url_for('.show_post', post_id=post_id))


@main_bp.route('/reply/comment/<int:comment_id>')
@login_required
@permission_required('COMMENT')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(
        url_for('.show_post', post_id=comment.post_id, reply=comment_id,
                user=comment.user.name) + '#comment-form')


@main_bp.route('/delete/post/<int:post_id>', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('微博已删除', 'info')

    next_post = Post.query.with_parent(post.user).filter(
        Post.id < post_id).order_by(Post.id.desc()).first()
    if next_post is None:
        next_post = Post.query.with_parent(post.user).filter(
            Post.id > post_id).order_by(Post.id.asc()).first()
        if next_post is None:
            return redirect(url_for('user.index', username=post.user.username))
        return redirect(url_for('.show_post', post_id=next_post.id))
    return redirect(url_for('.show_post', post_id=next_post.id))


@main_bp.route('/delete/comment/<int:comment_id>', methods=['POST'])
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.post.user and current_user != comment.user:
        abort(403)

    db.session.delete(comment)
    db.session.commit()
    flash('评论已删除', 'info')
    return redirect(url_for('.show_post', post_id=comment.post_id))


@main_bp.route('/tag/<int:tag_id>', defaults={'order': 'by_time'})
@main_bp.route('/tag/<int:tag_id>/<order>')
def show_tag(tag_id, order):
    tag = Tag.query.get_or_404(tag_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MANAGE_COMMENT_PER_PAGE']
    order_rule = 'time'

betterme/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
    <title>{% block title %}{% endblock %} - BetterMe</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    {% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% endblock styles %}
    {% endblock head %}
</head>

<body>
    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <img src="{{ url_for('static', filename='favicon.ico') }}" alt="BetterMe">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('main.index', '主页') }}
                    {{ render_nav_item('main.explore', '发现') }}

                    <form class="form-inline my-2 my-lg-0" action="{{ url_for('main.search') }}">
                        <input type="search" name="t" class="form-control mr-sm-1" placeholder="……" required>
                        <button class="btn btn-light my-2 my-sm-0" type="submit">
                            <span class="oi oi-magnifying-glass"></span>
                        </button>
                    </form>
                </div>
                <div class="navbar-nav ml-auto">
                    {{ render_nav_item('main.upload', '发微博') }}
                    {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('main.show_notifications', filter='unread') }}">
                        <span class="oi oi-bell"></span>
                        <span id="notification-badge"
                            class="{% if notification_count == 0 %}hide{% endif %} badge badge-danger badge-notification"
                            data-href="{{ url_for('ajax.notifications_count') }}">{{ notification_count }}</span>
                    </a>
                    <img src="{{ url_for('main.get_avatar', filename=current_user.s_avatar) }}">
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                            aria-expanded="false">
                            {{ current_user.name }}<span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('user.index', username=current_user.username) }}">
                                <span class="oi oi-person"></span> 个人界面
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('user.edit_profile') }}">
                                <span class="oi oi-cog"></span> 个人设置
                            </a>
                            {% if current_user.can('MODERATE') %}
                            <a class="dropdown-item" href="{{ url_for('admin.index') }}">
                                <span class="oi oi-dashboard"></span> 后台
                            </a>
                            {% endif %}
                            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                <span class="oi oi-power-standby"></span> 注销
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <a class="btn btn-outline-primary" href="{{ url_for('auth.login') }}">登陆</a>&nbsp;&nbsp;
                    <a class="btn btn-primary" href="{{ url_for('auth.register') }}">注册 BetterMe</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    {% endblock %}

    <main>
        <div class="container">
            {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
            {% endfor %}
            {% block content %}{% endblock %}
            {% block footer %}
            <footer>
                <p class="float-left">
                    <small>&copy; 2018
                        <a href="http://www.balthasar.cn" title="Written by lianziqt">lianziqt</a> -
                        <a href="https://github.com/lianziqt/BetterMe" title="Fork me on GitHub">GitHub</a> -
                    </small>
                </p>
                <p class="float-right">
                    <small>Remember every wonderful moment to be a better man.</small>
                </p>
            </footer>
            {% endblock %}
        </div>
    </main>
    <div id="toast"></div>
    {% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    {{ moment.locale(auto_detect=True) }}
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script type="text/javascript">
        var csrf_token = "{{ csrf_token() }}";
        {% if current_user.is_authenticated %}
        var is_authenticated = true;
        {% else %}
        var is_authenticated = false;
        {% endif %}
    </script>
    {% endblock %}

</body>

</html>

betterme/templates/macros.html
{% macro post_card(post) %}

<div class="card">
    {% if post.photos %}
    <a  href="{{ url_for('main.show_post', post_id=post.id) }}">
    <img src="{{ url_for('main.get_first_image', post_id=post.id) }}" class="card-img-top" >
    </a>
    {% endif %}
    <div class="card-body">
        <p class="card-text">{{ post.body }}</p>
        <hr>
        <div class="row">
            <div class="col-md-3">
                <a href="{{ url_for('user.index', username=post.user.username) }}">
                    <img class="" 
                    src="{{ url_for('main.get_avatar', filename=post.user.s_avatar) }}">
                </a>
            </div>
            <div class="col-md-9">
                    <h6>
                    <a href="{{ url_for('user.index', username=post.user.username) }}">{{ post.user.name }}</a>
                    </h6>
            </div>
        </div>
    </div>
    <div class="card-footer">
    <a  href="{{ url_for('main.show_post', post_id=post.id) }}">
        <small><span class="oi oi-comment-square"></span> {{ post.comments|length }}</small>
        {% if post.collectors %}
        <small><span class="oi oi-heart"></span> {{ post.collectors|length }} </small>
        {% endif %}
        </a>
        <small class="text-muted">at {{ moment(post.timestamp).format('LL') }}</small>
    </div>
</div>

{% endmacro %}

{% macro show_post_photos(photos) %}
    {% for photo in photos %}
    {% if loop.index % 3 == 1 %}
        <div class="row">
    {% endif %}
    <div class="col-sm-4">
        <div class="card">
            <a href="{{ url_for('main.get_image', filename=photo.filename, user_id=photo.user.id) }}" target="_blank">
                <img class="card-img-top" src="{{ url_for('main.get_image', filename=photo.s_filename, user_id=photo.user.id) }}">
            </a>
        </div>
    </div>
    {% if loop.index % 3 == 0 or loop.last %}
    </div>
    {% endif %}
    {% endfor %}
{% endmacro %}

{% macro follow_button(user) %}
    {% if current_user.is_authenticated %}
        {% if user != current_user %}
        <button data-id="{{ user.id }}"
                data-href="{{ url_for('ajax.unfollow', username=user.username) }}"
                class="{% if not current_user.is_follow(user) %}hide{% endif %} btn btn-dark btn-sm unfollow-btn">
            取消关注
        </button>
        <button data-id="{{ user.id }}"
                data-href="{{ url_for('ajax.follow', username=user.username) }}"
                class="{% if current_user.is_follow(user) %}hide{% endif %} btn btn-primary btn-sm follow-btn">
            关注
        </button>
        {% endif %}
    {% else %}
        <form class="inline" method="POST" action="{{ url_for('user.follow', username=user.username) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-outline-secondary btn-sm">
                关注
            </button>
        </form>
    {% endif %}
{% endmacro %}

{% macro user_card(user) %}
<div class="card bg-light mb-3 w-100">
        <div class="card-body">
            <div class="row">
                <a href="{{ url_for('user.index', username=user.username) }}">
                    <img class="sidebar-avatar rounded avatar-m"
                         src="{{ url_for('main.get_avatar', filename=user.m_avatar) }}">
                </a>
                <div class="sidebar-profile">
                    <h6 class="card-title">
                        <a href="{{ url_for('user.index', username=user.username) }}">{{ user.name }}</a>
                    </h6>
                    <p class="card-subtitle mb-2 text-muted">{{ user.username }}</p>
                    {{ follow_button(user) }}
                </div>
            </div>
        </div>
    </div>
{% endmacro %}